[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
orderly_oapp = "9qrP7gUnchdY9eJqKWAa7xYqj9ve6XGi7jkiCFtCtjW7"
vault = "BKXJXj9RkGuXWrFcQV7vFgvWnEc7ajD3yW7mvvaL3C7A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dmitry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
