[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
vault = "HthvNeLQjkQV4PvPQq78G6DVeK6ozvhYLw2cNGNVuW39"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dmitry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
